apiVersion: apps/v1
kind: Deployment
metadata:
  name: crawlnitube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crawlnitube
  template:
    metadata:
      labels:
        app: crawlnitube
    spec:
      containers:
      - name: crawlnitube
        image: crawlnitube:latest
        imagePullPolicy: Never
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 4000

